name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{ matrix.otp }}

    strategy:
      fail-fast: false
      matrix:
        otp: ["28.0", "27.3", "26.2", "25.3"]
        os: ["ubuntu-22.04"]

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: rebar3 compile

      - name: xref
        run: rebar3 xref

      - name: Eunit test
        run: rebar3 eunit

      - name: Common test
        run: rebar3 ct

      - name: Generate docs
        run: rebar3 edoc

      - name: Dialyze
        run: rebar3 dialyzer
